version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii_web
    volumes:
      - ./:/var/www/html
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8000:80"
    depends_on:
      - db 
    networks:
      - yii-docker-network

  db:
    image: mysql:5.6
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: 'yii_database'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - yii-docker-network

volumes:
  db_data:

networks:
  yii-docker-network:
    driver: bridge